#!/usr/bin/env python3
"""Onboard or refresh a project entry under chief-of-staff/projects/<name>/.

The chief of staff keeps a local, read-only *mirror* of the state it needs to
orchestrate each project it manages: what the project is, its vision, its live
git/agent status, its past decisions, and a copy of its LESSONS.md.

  overview.md   created once, never clobbered  (human-owned: about + vision + focus)
  decisions.md  created once, never clobbered  (human-owned: ADR log)
  lessons.md    overwritten every sync         (MIRROR of <src>/LESSONS.md)
  status.md     overwritten every sync         (AUTO snapshot: git + PRs + agents)

Usage:
  python scripts/sync-project.py <repo-path-or-name> [<more> ...]
  python scripts/sync-project.py --all        # every git repo under ~/Projects
  python scripts/sync-project.py --lessons     # only repos that have a LESSONS.md

Idempotent: re-run any time to refresh the mirrored/auto files. Human-owned
files are only created when missing, so edits are safe across syncs.
"""
import os, sys, json, subprocess, datetime

HOME = os.path.expanduser("~")
PROJECTS_ROOT = os.path.join(HOME, "Projects")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # chief-of-staff/
DEST_ROOT = os.path.join(REPO, "projects")
# Repos the chief does not manage as products: itself and the shared template infra.
SKIP = {"chief-of-staff", "agentic-workflow-template"}


def run(args, cwd=None):
    """Run a command, return (stdout, ok). Never raises."""
    try:
        p = subprocess.run(args, cwd=cwd, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=30)
        return p.stdout.strip(), p.returncode == 0
    except Exception:
        return "", False


def today():
    return datetime.date.today().isoformat()


def resolve(token):
    """A path or a bare name under ~/Projects -> absolute repo path (or None)."""
    for cand in (token, os.path.join(PROJECTS_ROOT, token)):
        cand = os.path.abspath(cand)
        if os.path.isdir(os.path.join(cand, ".git")):
            return cand
    return None


def about_from_docs(src):
    """First real paragraph of README.md, else AGENTS.md, as a seed 'about'."""
    for fn in ("README.md", "AGENTS.md"):
        p = os.path.join(src, fn)
        if not os.path.isfile(p):
            continue
        para = []
        for line in open(p, encoding="utf-8", errors="replace"):
            s = line.strip()
            if s.startswith("#") or s.startswith(">"):
                if para:
                    break
                continue
            if not s:
                if para:
                    break
                continue
            para.append(s)
        if para:
            return " ".join(para)
    return "_TODO: one-line description of what this project is._"


def herdr_agents_for(src):
    out, ok = run(["herdr", "agent", "list"])
    if not ok:
        return None
    try:
        agents = json.loads(out)["result"]["agents"]
    except Exception:
        return None
    keep = []
    srcn = os.path.normcase(os.path.normpath(src))
    for a in agents:
        cwd = os.path.normcase(os.path.normpath(a.get("cwd", "")))
        if cwd.startswith(srcn):
            keep.append(a)
    return keep


def write_status(dest, src, name):
    branch, _ = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=src)
    log, _ = run(["git", "log", "-8", "--format=- `%h` %s  _(%cd)_", "--date=short"], cwd=src)
    wt, _ = run(["git", "worktree", "list"], cwd=src)
    dirty, _ = run(["git", "status", "--short"], cwd=src)
    prs, prok = run(["gh", "pr", "list", "--state", "open",
                     "--json", "number,title,headRefName,isDraft,mergeable",
                     "--limit", "50"], cwd=src)
    pr_lines = "_gh unavailable or no remote._"
    if prok and prs:
        try:
            arr = json.loads(prs)
            if arr:
                pr_lines = "\n".join(
                    "- #%s %s `%s` — mergeable=%s%s" % (
                        p["number"], p["title"], p["headRefName"],
                        p.get("mergeable", "?"), " *(draft)*" if p.get("isDraft") else "")
                    for p in arr)
            else:
                pr_lines = "_No open PRs._"
        except Exception:
            pass

    agents = herdr_agents_for(src)
    if agents is None:
        ag_lines = "_herdr not reachable._"
    elif not agents:
        ag_lines = "_No herdr agents currently on this project._"
    else:
        ag_lines = "\n".join(
            "- `%s` **%s** — %s" % (
                a.get("pane_id", "?"), a.get("agent_status", "?"),
                a.get("terminal_title_stripped", "").strip() or a.get("agent", ""))
            for a in agents)

    body = f"""<!-- AUTO-GENERATED by scripts/sync-project.py — DO NOT EDIT. Re-run to refresh. -->
# {name} — status snapshot

- Synced: {today()}
- Source: `{src}`
- Current branch: `{branch or '?'}`

## Working tree
{"```\n" + dirty + "\n```" if dirty else "_Clean._"}

## Recent commits
{log or "_none_"}

## Worktrees
```
{wt or "(none)"}
```

## Open PRs
{pr_lines}

## Live herdr agents
{ag_lines}
"""
    open(os.path.join(dest, "status.md"), "w", encoding="utf-8").write(body)


def write_lessons_mirror(dest, src, name):
    srcp = os.path.join(src, "LESSONS.md")
    banner = (f"<!-- MIRROR of {srcp}\n"
              f"     Source of truth is that file, in the project's own repo.\n"
              f"     Overwritten by scripts/sync-project.py — do not edit here. "
              f"Synced {today()}. -->\n\n")
    if os.path.isfile(srcp):
        content = open(srcp, encoding="utf-8", errors="replace").read()
        open(os.path.join(dest, "lessons.md"), "w", encoding="utf-8").write(banner + content)
        return True
    open(os.path.join(dest, "lessons.md"), "w", encoding="utf-8").write(
        banner + f"# {name} — lessons (mirror)\n\n_No LESSONS.md in the source repo yet._\n")
    return False


def write_overview_if_missing(dest, src, name):
    p = os.path.join(dest, "overview.md")
    if os.path.exists(p):
        return False
    open(p, "w", encoding="utf-8").write(f"""# {name}

> Human-owned. Created once by sync-project.py; never overwritten. Keep it current.

## About

{about_from_docs(src)}

## Vision

_Where this project is headed, and why it matters. TODO._

## Current focus

_What the chief of staff should be pushing on right now. TODO._

## Constraints & gotchas the chief must respect

- See [`lessons.md`](lessons.md) (mirror of the project's LESSONS.md).
- _TODO: anything orchestration-specific (build host, device, do-not-touch areas)._
""")
    return True


def write_decisions_if_missing(dest, name):
    p = os.path.join(dest, "decisions.md")
    if os.path.exists(p):
        return False
    open(p, "w", encoding="utf-8").write(f"""# {name} — decisions

> Human-owned decision log: the calls the owner has made and *why*, so the chief
> and its staff don't relitigate settled ground. Newest on top. Dates absolute.

## YYYY-MM-DD — <decision title>

- Status: accepted
- Context: _what forced the choice_
- Decision: _what we chose_
- Why: _the reasoning; the alternatives rejected and why_
- Consequences: _what this makes easier / harder_
""")
    return True


def sync_one(src):
    name = os.path.basename(src.rstrip("/\\"))
    if name in SKIP:
        return None
    dest = os.path.join(DEST_ROOT, name)
    os.makedirs(dest, exist_ok=True)
    made_ov = write_overview_if_missing(dest, src, name)
    made_dc = write_decisions_if_missing(dest, name)
    had_less = write_lessons_mirror(dest, src, name)
    write_status(dest, src, name)
    flags = "".join([
        "O" if made_ov else "o", "D" if made_dc else "d",
        "L" if had_less else "-", "S"])
    print(f"  [{flags}] projects/{name}")
    return name


def iter_targets(argv):
    if "--all" in argv or "--lessons" in argv:
        only_lessons = "--lessons" in argv
        for n in sorted(os.listdir(PROJECTS_ROOT)):
            p = os.path.join(PROJECTS_ROOT, n)
            if not os.path.isdir(os.path.join(p, ".git")) or n in SKIP:
                continue
            if only_lessons and not os.path.isfile(os.path.join(p, "LESSONS.md")):
                continue
            yield p
        return
    for tok in argv:
        if tok.startswith("-"):
            continue
        r = resolve(tok)
        if r:
            yield r
        else:
            print(f"  !! not a git repo: {tok}", file=sys.stderr)


def main():
    argv = sys.argv[1:]
    if not argv:
        sys.exit(__doc__)
    print("legend: [Overview Decisions Lessons Status]  UPPER=created/mirrored lower=kept")
    for src in iter_targets(argv):
        sync_one(src)
    print("done.")


if __name__ == "__main__":
    main()
